### ISSUE TITLE
show whole items 

### ISSUE THREAD

**Issue by cococa** [rubensousa/BottomSheetExample#2]
if i add 10 item into recycleView, i want show 10 item when i called BottomSheetDialog.show(),not use drag,Can you help me ?THANKS!

**Comment by rubensousa** [comment]
Please, take a look at this library: https://github.com/rubensousa/BottomSheetBuilder
It handles that for you already :)

**Comment by rubensousa** [comment]
Please, take a look at: https://github.com/rubensousa/BottomSheetExample/blob/master/app/src/main/java/com/github/rubensousa/bottomsheetexample/ui/FullBottomSheetDialogFragment.java
